title: Marcelo L. Lopez Photography | Bronx NYC Portrait & Headshot Photographer
url: https://mlopezphoto.com
baseurl: ""

author: Marcelo Lopez
description: Bronx, NYC based portrait photographer specializing in headshots, editorial, and political creatives. Book your session today!

include: ['_pages']

collections_dir: series

collections:
  davgil:
    output: true
  editorial:
    output: true
  fun:
    output: true
  headshots:
    output: true
  politics:
    output: true

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - LICENSE.txt
  - README.md
